# Generated by Django 5.2.9 on 2025-12-17 14:47

import find_primes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrimeNumberRequests',
            fields=[
                ('request_id', models.CharField(default=find_primes.models.generate_uuid, max_length=255, primary_key=True, serialize=False)),
                ('no_of_primes', models.PositiveIntegerField()),
                ('requested_at', models.DateField(auto_now_add=True)),
                ('status', models.CharField(max_length=255, validators=[find_primes.models.validate_prime_number_request_status])),
                ('completed_at', models.DateField(blank=True, null=True)),
                ('result', models.TextField(default='{}')),
            ],
        ),
    ]
