# Generated by Django 5.2.9 on 2025-12-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_primes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='primenumberrequests',
            name='celery_req_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
