# Generated by Django 5.2.9 on 2025-12-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_primes', '0002_primenumberrequests_celery_req_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primenumberrequests',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='primenumberrequests',
            name='requested_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
